name: ga4_analytics
version: '1.0.0'
config-version: 2

profile: ga4_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  ga4_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
